// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpHwSwfJI6Toj5DZqMs0AleS9YIWEk_u4',
    appId: '1:378187962780:web:404551d7e24c552f279059',
    messagingSenderId: '378187962780',
    projectId: 'sadeem-b0fb8',
    authDomain: 'sadeem-b0fb8.firebaseapp.com',
    storageBucket: 'sadeem-b0fb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZpFRn_hxtvuFsNov2nUaoLVr0nlzhZM',
    appId: '1:378187962780:android:3f6928e7f9b82520279059',
    messagingSenderId: '378187962780',
    projectId: 'sadeem-b0fb8',
    storageBucket: 'sadeem-b0fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQ-vlHipAIuQYPCitc_ZANdieOkQusrY',
    appId: '1:378187962780:ios:3243d523a7078019279059',
    messagingSenderId: '378187962780',
    projectId: 'sadeem-b0fb8',
    storageBucket: 'sadeem-b0fb8.appspot.com',
    iosBundleId: 'com.example.nasaSpaceAppsChallenge',
  );
}
